
input_features:
  -    
    name: RAD51
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore

  -
    name: Cyc_D1
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore

  -
    name: Vimentin
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
    
  -
    name: aSMA
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
    

  -
    name: E_cadherin
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
    

  -
    name: ER_alpha
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
    

  -
    name: PR
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
    

  -
    name: EGFR
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore

  -
    name: Rb
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
    

  -
    name: CD45
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore

  -
    name: Ki67
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore

  -
    name: CK19
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
      
  -
    name: p21
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore
    
  -
    name: CK14
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore


  -
    name: AR
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore


  -
    name: cPARP
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore


  -
    name: CK17
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore


  -
    name: CK7
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore

  -
    name: HER2
    type: numerical
    
    num_layers: 10
    activation: relu
    dropout: 0
    normalization: zscore



output_features:
  -
    name: ERK1_1
    type: numerical
    loss:
      type: mean_squared_error
    activation: relu
    weights_initializer: glorot_uniform
    encoder: dense
    num_fc_layers: 2
    fc_size: 64
    

training:
 batch_size: 96
 epochs: 100