model_type: gbm
training:
  early_stop: 10

hyperopt:

  goal: minimize
  output_feature: CK19
  metric: mean_absolute_error
  split: validation
  parameters:
    trainer.learning_rate:
      space: loguniform
      lower: 0.001
      upper: 0.1

  search_alg:
    type: hyperopt
  executor:
    type: ray
    num_samples: 10
    cpu_resources_per_trial: 1

    