# NOTE: Generated by ChatGPT with the prompt "write a python script that uses pandas to find all the common columns in CSVs in a directory"

'''
This script uses the os module to list all files in the given directory that end with '.csv', 
reads each of these files into a pandas dataframe, and then uses a set intersection to find 
the common columns among all dataframes. The final result is a list of the common columns.
'''

import os
import pandas as pd


def find_common_columns(directory):
    csv_files = [f for f in os.listdir(directory) if f.endswith('.csv')]
    dfs = [pd.read_csv(os.path.join(directory, f)) for f in csv_files]
    common_columns = set(dfs[0].columns)
    for df in dfs[1:]:
        common_columns &= set(df.columns)
    return list(common_columns)


directory = '../data/Tumor/'
print(','.join(find_common_columns(directory)))
